### PR TITLE
Cpp98 compatibility

### LINKED ISSUE #57: is_valid does not allow lvalue references
https://github.com/mat007/turtle/blob/e92f52821da312c5e30b447c8046893e576aefca/include/turtle/detail/expectation_template.hpp#L207 makes it impossible to have functions taking e.g. `const Foo&` as this fails with

`error: non-const lvalue reference to type '::boost::rv<const Foo&>' cannot bind to a value of unrelated type 'const Foo'`

I guess that should just be regular params as per the signature?

### PR DESCRIPTION
**Pull request by Flamefire**
Supersedes #58 and fixes #57.

It fixes the arguments used. The general rules are:

- For instances either T&& or const T& depending on C++11/98
- References left as is
- Encapsulate differences into `move_helper.hpp`

Compiles locally in C++98 and C++11. Includes #54 as it belongs to this topic.

### CODE REVIEW

File: include/turtle/detail/move_helper.hpp [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+    struct ref_arg
+    {
+        typedef typename boost::conditional<
+          boost::is_reference<T>::value,
+          T,
+          typename boost::add_rvalue_reference<T>::type >::type type;
+    };
+
+    template< typename T >
+    inline T&& move_if_not_lvalue_reference(typename boost::remove_reference<T>::type& t)
```
Comment (mat007) [inline include/turtle/detail/move_helper.hpp]: I don't think `inline` is needed or even brings any value for template functions.

File: include/turtle/detail/move_helper.hpp [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+    {
+        typedef T type;
+    };
+    template< typename T >
+    struct ref_arg
+    {
+        typedef typename boost::conditional<
+          boost::is_reference<T>::value,
+          T,
+          typename boost::add_rvalue_reference<T>::type >::type type;
```
Comment (mat007) [inline include/turtle/detail/move_helper.hpp]: Missing spaces around `T` (sorry it's the project coding conventions :p).
They are other occurrences of this in this file.

File: include/turtle/detail/move_helper.hpp [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+    };
+    template< typename T >
+    struct ref_arg
+    {
+        typedef typename boost::conditional<
+          boost::is_reference<T>::value,
+          T,
+          const typename boost::add_reference<T>::type >::type type;
+    };
+    // Define as noop
```
Comment (mat007) [inline include/turtle/detail/move_helper.hpp]: nit: in my opinion the comment could be removed

File: include/turtle/matcher.hpp [hunk 4]
```diff
@@ -26,7 +28,7 @@ namespace mock
         explicit matcher( Expected expected )
             : expected_( expected )
         {}
-        bool operator()( const Actual& actual )
+        bool operator()( typename boost::add_reference<const Actual>::type actual )
```
Comment (mat007) [inline include/turtle/matcher.hpp]: Spaces within `<…>` here as well.

File: include/turtle/matcher.hpp [hunk 5]
```diff
@@ -91,9 +93,9 @@ namespace mock
         explicit matcher( const Functor& f )
             : c_( f )
         {}
-        bool operator()( BOOST_RV_REF(Actual) actual )
+        bool operator()( typename detail::ref_arg< Actual >::type actual )
         {
-            return c_( boost::forward< Actual >( actual ) );
+            return c_( ::mock::detail::move_if_not_lvalue_reference< typename detail::ref_arg< Actual >::type >( actual ) );
```
Comment (mat007) [inline include/turtle/matcher.hpp]: I know this might not be very clever but at the moment the project uses `mock::…` i.e. without prefixing with `::`.

File: include/turtle/detail/move_helper.hpp (hunk 1 above)
Comment (mat007) [reply include/turtle/detail/move_helper.hpp]: Aha I actually had read that SO question and I even upvoted the comment that says `The explicit specialization is not a template.` :)
I apparently believed the accepted answer was wrong also, as I had upvoted the other one as well… 🤔

Comment (mat007) [reply include/turtle/detail/move_helper.hpp]: A hint to what? That we reeeeally would like you to optimize the function call away please Mr compiler ? :)
Anyway it's no big deal and won't break user code, so we can leave it or remove it, whichever…

**Comment by Flamefire** [comment]
Rebased to master an squashed commits (even included the std::move one as your argument also applies to that)

**Comment by mat007** [comment]
Good point, thanks!
