### PR TITLE
Fix issue 115 null c string derefs

### LINKED ISSUE #115: Null dereferences when mocking C-style string arguments
Mocking methods / functions that take C-style string (i.e. `char*`) arguments can lead to null dereferences, in some cases where `nullptr` is expected and / or actually passed.

When a mock method / function is configured to expect a call with a non-null string, a `nullptr` dereference occurs in the case that the code under test incorrectly passes `nullptr`. Compare and contrast the behaviour of the following:

```
MOCK_FUNCTION( f, 1, void( const char* ) );

BOOST_FIXTURE_TEST_CASE( expect_non_null_get_non_null, mock::cleanup )
{
    mock::sequence s;
    MOCK_EXPECT( f ).once().in( s ).with( "correct" );

    f( "wrong" );

    mock::verify();
    // We are correctly told that the `code under test' called f() with the
    // string "wrong" when it should have passed "correct".
}

BOOST_FIXTURE_TEST_CASE( expect_non_null_get_null, mock::cleanup )
{
    mock::sequence s;
    MOCK_EXPECT( f ).once().in( s ).with( "test" );

    f( nullptr );

    mock::verify();
    // Bang! nullptr is dereferenced.
}
```

When a mock method / function is configured to expect character pointer `nullptr` to be passed to a C-style string argument, a `nullptr` dereference occurs, regardless of whether the code under test passes `nullptr` or a non-null string. Note that this does not occur when `nullptr_t` `nullptr` is expected, so is only a problem when e.g. a constant or definition that is more natural to the particular situation is used in the expectation, rather than explicitly expecting `nullptr`. Compare and contrast the behaviour of the following:

```
// From some third-party API header:
typedef const char* some_api_string;
#define SOME_API_NO_STRING ( (const char*) NULL )

MOCK_FUNCTION( f, 1, void( some_api_string ) );

BOOST_FIXTURE_TEST_CASE( expect_nullptr_get_null, mock::cleanup )
{
    mock::sequence s;
    MOCK_EXPECT( f ).once().in( s ).with( nullptr );

    f( SOME_API_NO_STRING );

    mock::verify();
    // We are correctly told that the test passed.
}

BOOST_FIXTURE_TEST_CASE( expect_null_get_null, mock::cleanup )
{
    mock::sequence s;
    MOCK_EXPECT( f ).once().in( s ).with( SOME_API_NO_STRING );

    f( SOME_API_NO_STRING );

    mock::verify();
    // Bang! nullptr is dereferenced.
}

BOOST_FIXTURE_TEST_CASE( expect_null_get_non_null, mock::cleanup )
{
    mock::sequence s;
    MOCK_EXPECT( f ).once().in( s ).with( SOME_API_NO_STRING );

    f( "wrong" );

    mock::verify();
    // Bang! nullptr is dereferenced.
}
```

These `nullptr` dereferences occur because there are no runtime checks for the `nullptr` cases in the matcher and serializer for C-style strings. Pull request to follow.

### PR DESCRIPTION
**Pull request by AlexSmithEtas**
This pull request fixes the cases of `nullptr` dereference when mocking C-style string (`char*`) arguments described in #115. It adds unit tests for the matching and serialization of C-style strings that are in fact `nullptr`. The new unit tests correctly fail before application of the fix, except for the new test of `mock::equal`, which was added merely as a regression test.

Fixes #115

### CODE REVIEW

File: include/turtle/matcher.hpp [hunk 1]
```diff
@@ -39,7 +39,12 @@ class matcher<const char*, const char*>
 {
 public:
     explicit matcher(const char* expected) : expected_(expected) {}
-    bool operator()(const char* actual) { return std::strcmp(actual, expected_) == 0; }
+    bool operator()(const char* actual)
+    {
+        if (nullptr == actual || nullptr == expected_)
```
Comment (mat007) [inline include/turtle/matcher.hpp:44]: Would it not be more generic if it were
```suggestion
        if (!actual || !expected_)
```
?

File: include/turtle/stream.hpp [hunk 2]
```diff
@@ -106,7 +106,13 @@ namespace detail {
     {
         s << '"' << str << '"';
     }
-    inline void serialize(stream& s, const char* const str) { s << '"' << str << '"'; }
+    inline void serialize(stream& s, const char* const str)
+    {
+        if (nullptr != str)
```
Comment (mat007) [inline include/turtle/stream.hpp:111]: What about
```suggestion
        if (str)
```
?
Or is that considered back practice these days (sorry, I haven’t done any C++ in years)?

I think it should at least be
```suggestion
        if (str != nullptr)
```
?

File: test/test_log.cpp [hunk 3]
```diff
@@ -89,6 +89,14 @@ BOOST_AUTO_TEST_CASE(strings_are_serialized_with_double_quotes)
     BOOST_CHECK_EQUAL("\"string\"", to_string(std::string("string")));
 }
 
+BOOST_AUTO_TEST_CASE(null_c_strings_are_serialized_to_nullptr)
+{
+    const char* const null_str = nullptr;
+    BOOST_CHECK_EQUAL("nullptr", to_string(null_str));
+    // Note the lack of double quotes in the output, as opposed to when the
+    // string "nullptr" is serialized.
```
Comment (mat007) [inline test/test_log.cpp:97]: nit: I’m not sure we need that comment, do we?
If we really need to emphasize this, what about
```suggestion
    BOOST_CHECK_NE("\"nullptr\"", to_string(null_str));
```
?
That’s a little odd following an `BOOST_CHECK_EQUAL` though, I suppose 😅

File: test/test_matcher.cpp [hunk 4]
```diff
@@ -36,14 +36,15 @@ BOOST_AUTO_TEST_CASE(ref_to_int_and_int_can_be_compared)
...
-    fixture() : text("same text"), actual(text.c_str())
+    fixture() : text("same text"), actual(text.c_str()), null_str(nullptr)
     {
         const char* static_string = "same text";
         BOOST_REQUIRE(actual != static_string);
         BOOST_REQUIRE(actual == std::string(static_string));
     }
     std::string text;
     const char* actual;
+    const char* null_str;
```
Comment (mat007) [inline test/test_matcher.cpp:47]: I’m not sure this needs to be factor out in the fixture, given it’s only used once?

File: test/test_matcher.cpp [hunk 5]
```diff
@@ -75,6 +76,13 @@ BOOST_FIXTURE_TEST_CASE(const_char_pointer_and_std_string_can_be_compared, fixtu
     BOOST_CHECK(!match(std::string("different text"), actual));
 }
 
+BOOST_FIXTURE_TEST_CASE(null_const_char_pointers_can_be_compared, fixture)
```
Comment (mat007) [inline test/test_matcher.cpp:79]: I’m not sure this even needs a fixture?

**Review by mat007 — COMMENTED** [review]
Thanks for the PR!

File: test/test_log.cpp (hunk 3 above)
Comment (Flamefire) [reply test/test_log.cpp:97]: How about adding `to_string("nullptr")` as a `BOOST_CHECK_EQUAL` right below instead of the comment to demonstrate it instead of explaining it?

File: include/turtle/stream.hpp (hunk 2 above)
Comment (AlexSmithEtas) [reply include/turtle/stream.hpp:111]: Again, merely force of habbit. I'm used to the defensive style of putting the constant on the left in comparisons, so that when one accidentally types `if (nullptr = str)` instead of `if (nullptr == str)` the compiler catches it, unlike `if (str = nullptr)` which silently does something unintended. Again, if treating pointers as if they are booleans is your preferred style then I'm very happy to change this to match.

**Review by Flamefire — CHANGES_REQUESTED** [review]
Thanks for the PR! I tested it and it does work as expected and tests cover the issue and changes well.

I agree with @mat007 that checking for a NULL pointer should be done via `if(ptr)` or `if(!ptr)` and the fixture in the test is not required (I'll remove it from the other tests once this is merged)

> I'm used to having to worry about embedded targets where one cannot assume that the null pointer is zero.

Out of curiosity: Does there really exist a target where `if(ptr)` would trigger on a null pointer? My understanding of the standard is that a null pointer would fail such a test even if the null pointer does not numerically equal zero.

File: test/test_log.cpp (hunk 3 above)
Comment (AlexSmithEtas) [reply test/test_log.cpp:97]: Yes, demonstrating the difference rather than attempting to explain it makes a lot of sense and has the advantage of proving it to be the case into the bargain.

File: test/test_matcher.cpp (hunk 4 above)
Comment (AlexSmithEtas) [reply test/test_matcher.cpp:47]: True. Now that I look at this again I think I was trying too hard to fit into the existing pattern of these tests. I agree that it would be simpler just to define this in the one test that uses it.

File: test/test_matcher.cpp (hunk 5 above)
Comment (AlexSmithEtas) [reply test/test_matcher.cpp:79]: I agree that this would indeed be simpler as a regular test case that defines `null_str` itself.

**Comment by AlexSmithEtas** [comment]
> Out of curiosity: Does there really exist a target where `if(ptr)` would trigger on a null pointer? My understanding of the standard is that a null pointer would fail such a test even if the null pointer does not numerically equal zero.

Unfortunately, embedded compilers aren't always the best for strict standards compliance, so yes, there are a few obscure targets out there where `if(ptr)` gives true for the valid address of zero and false for NULL / nullptr. They are, however, surely not of relevance for this project so I've changed the code to match your preferred style.

**Review by Flamefire — APPROVED** [review]

**Review by mat007 — APPROVED** [review]
Thanks!

**Comment by Flamefire** [comment]
Appveyor failure is unrelated:

```
Generating Output File: C:\projects\turtle\doc\bin\mock.xml
xslt-xsltproc.windows C:\projects\turtle\doc\bin\mock.docbook
error : Unknown IO error
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/common/common.xsl"
compilation error: file file:///C:/projects/turtle/bin/turtle/boostbook/xsl/docbook.xsl line 12 element import
xsl:import : unable to load http://docbook.sourceforge.net/release/xsl/current/common/common.xsl
```
