### PR TITLE
Fix unused variable warning in non-threadsafe builds

### LINKED ISSUE #56: Clang throws unused variable warnings
Using clang 3.5

```
contrib/turtle/include/turtle/detail/function_impl_template.hpp:66:18: error: unused variable '_' [-Werror,-Wunused-variable]
            lock _( mutex_ );
                 ^
contrib/turtle/include/turtle/detail/function_impl_template.hpp:83:18: error: unused variable '_' [-Werror,-Wunused-variable]
            lock _( mutex_ );
                 ^
contrib/turtle/include/turtle/detail/function_impl_template.hpp:199:18: error: unused variable '_' [-Werror,-Wunused-variable]
            lock _( mutex_ );
                 ^
contrib/turtle/include/turtle/detail/function_impl_template.hpp:206:18: error: unused variable '_' [-Werror,-Wunused-variable]
            lock _( mutex_ );
                 ^
contrib/turtle/include/turtle/detail/function_impl_template.hpp:215:18: error: unused variable '_' [-Werror,-Wunused-variable]
            lock _( mutex_ );
                 ^
contrib/turtle/include/turtle/detail/function_impl_template.hpp:251:18: error: unused variable '_' [-Werror,-Wunused-variable]
            lock _( mutex_ );
                 ^
contrib/turtle/include/turtle/detail/function_impl_template.hpp:261:18: error: unused variable '_' [-Werror,-Wunused-variable]
            lock _( impl.mutex_ );
```

### PR DESCRIPTION
**Pull request by Flamefire**
Avoids unused variable warnings for non-thread-safe builds

Fixes #56

### CODE REVIEW

**Comment by Flamefire** [comment]
Given that this seems to be fixed in Clang 4 I'd close this to avoid the macros. What I'd suggest including though are the changes to `lock` (ctors and mutable)

**Comment by mat007** [comment]
> What I'd suggest including though are the changes to lock (ctors and mutable)

Sure, but that seems to break on appveyor?

**Comment by Flamefire** [comment]
Seems I was wrong and Clang 5 DOES warn (again?): https://travis-ci.com/Return-To-The-Roots/s25client/jobs/160379940#L2172

**Comment by Flamefire** [comment]
> Sure, but that seems to break on appveyor?

Found the issue: `lock` gets "copied" but the copy ctor is a destructive copy and should be a move instead.

**Comment by Flamefire** [comment]
@mat007 Can this be merged or are any changes required?

File: include/turtle/detail/function_impl_template.hpp [hunk 1]
```diff
@@ -97,40 +97,52 @@ namespace detail
 
         struct wrapper : wrapper_base< R, expectation_type >
         {
+        private:
+            typedef wrapper_base< R, expectation_type > Base;
```
Comment (mat007) [inline include/turtle/detail/function_impl_template.hpp]: This needs to be `base_type` instead of `Base` if I correctly remember the coding conventions.

File: include/turtle/detail/function_impl_template.hpp [hunk 2]
```diff
@@ -97,40 +97,52 @@ namespace detail
...
+            BOOST_MOVABLE_BUT_NOT_COPYABLE(wrapper)
+        public:
```
Comment (mat007) [inline include/turtle/detail/function_impl_template.hpp]: nit: add a blank line before `public:`

File: include/turtle/detail/mutex.hpp [hunk 3]
```diff
@@ -36,25 +38,32 @@ namespace detail
...
             m_->lock();
         }
-        lock( const lock& rhs )
-        {
-            m_.swap( rhs.m_ );
-        }
         ~lock()
         {
-            if( m_ )
+            if(m_)
```
Comment (mat007) [inline include/turtle/detail/mutex.hpp]: nit: this needs spaces

File: include/turtle/detail/function_impl_template.hpp [hunk 4]
```diff
@@ -97,40 +97,52 @@ namespace detail
 
         struct wrapper : wrapper_base< R, expectation_type >
```
Comment (mat007) [inline include/turtle/detail/function_impl_template.hpp]: nit: this could probably be a `class` now

File: include/turtle/detail/function_impl_template.hpp [hunk 5]
```diff
@@ -97,40 +97,52 @@ namespace detail
...
             wrapper( const boost::shared_ptr< mutex >& m, expectation_type& e )
                 : wrapper_base< R, expectation_type >( e )
                 , lock_( m )
             {}
-
-            wrapper once()
+            wrapper( BOOST_RV_REF( wrapper ) x )
+                : Base( x ), lock_( boost::move( x.lock_) )
+            {}
+            wrapper& operator=( BOOST_RV_REF( wrapper ) x)
```
Comment (mat007) [inline include/turtle/detail/function_impl_template.hpp]: nit: missing a space after `x`

File: include/turtle/detail/function_impl_template.hpp [hunk 6]
```diff
@@ -97,40 +97,52 @@ namespace detail
...
+            {
+                static_cast< Base& >( *this ) = x;
+                lock_ = boost::move( x.lock_);
```
Comment (mat007) [inline include/turtle/detail/function_impl_template.hpp]: nit: missing a space before `)`

File: include/turtle/detail/function_impl_template.hpp (hunk 1 above)
Comment (mat007) [reply include/turtle/detail/function_impl_template.hpp]: Not sure the typedef brings much, but it should probably be used consistently then (in the other constructor)

File: include/turtle/detail/mutex.hpp [hunk 7]
```diff
@@ -36,25 +38,32 @@ namespace detail
 
     struct lock
     {
+    private:
+        BOOST_MOVABLE_BUT_NOT_COPYABLE(lock)
+    public:
```
Comment (mat007) [inline include/turtle/detail/mutex.hpp]: nit: missing a blank line

File: include/turtle/detail/mutex.hpp [hunk 8]
```diff
@@ -36,25 +38,32 @@ namespace detail
...
+            if(m_)
                 m_->unlock();
         }
-
+        lock( BOOST_RV_REF( lock ) x )
+            : m_( x.m_ )
+        {
+            x.m_.reset();
+        }
+        lock& operator=( BOOST_RV_REF( lock ) x)
```
Comment (mat007) [inline include/turtle/detail/mutex.hpp]: nit: space missing after `x`

File: include/turtle/detail/mutex.hpp [hunk 9]
```diff
@@ -65,24 +74,30 @@ namespace mock
 {
 namespace detail
 {
-    struct mutex
+    struct mutex: boost::noncopyable
```
Comment (mat007) [inline include/turtle/detail/mutex.hpp]: nit: missing a space before `:`

File: include/turtle/detail/mutex.hpp [hunk 10]
```diff
@@ -65,24 +74,30 @@ namespace mock
...
     {
-        mutex()
-        {}
-        void lock()
-        {}
-        void unlock()
-        {}
+        void lock(){}
+        void unlock(){}
```
Comment (mat007) [inline include/turtle/detail/mutex.hpp]: nit: revert the formatting change maybe?

File: include/turtle/detail/mutex.hpp [hunk 11]
```diff
@@ -65,24 +74,30 @@ namespace mock
...
     };
-    struct scoped_lock
+    // Dummy lock classes.
+    // Note: Ctor + Dtor make it RAII classes for compilers and avoid unused variable warnings
+    struct scoped_lock: boost::noncopyable
```
Comment (mat007) [inline include/turtle/detail/mutex.hpp]: nit: needs a space before `:`

File: include/turtle/detail/mutex.hpp [hunk 12]
```diff
@@ -65,24 +74,30 @@ namespace mock
...
-        void lock()
-        {}
-        void unlock()
-        {}
+        void lock(){}
+        void unlock(){}
     };
-    struct scoped_lock
+    // Dummy lock classes.
+    // Note: Ctor + Dtor make it RAII classes for compilers and avoid unused variable warnings
```
Comment (mat007) [inline include/turtle/detail/mutex.hpp]: nit: `Ctor` -> `Constructor` and `Dtor` -> `Destructor`, also `Note:` does not bring much (it's a comment, which by definition is sort of a note in the code 😄 )

File: include/turtle/detail/mutex.hpp [hunk 13]
```diff
@@ -65,24 +74,30 @@ namespace mock
...
+    struct scoped_lock: boost::noncopyable
     {
-        scoped_lock( mutex& )
-        {}
+        scoped_lock( mutex& ){}
+        ~scoped_lock(){}
```
Comment (mat007) [inline include/turtle/detail/mutex.hpp]: nit: revert the formatting changes as well?

File: include/turtle/detail/mutex.hpp [hunk 14]
```diff
@@ -65,24 +74,30 @@ namespace mock
...
     };
-    struct lock
+    struct lock: boost::noncopyable
```
Comment (mat007) [inline include/turtle/detail/mutex.hpp]: nit: missing space before `:`

Comment (mat007) [reply include/turtle/detail/mutex.hpp]: This is probably worth having a `class` instead of a `struct` now that it has visibility modifiers?

File: include/turtle/detail/mutex.hpp [hunk 15]
```diff
@@ -65,24 +74,30 @@ namespace mock
...
     {
-        lock( const boost::shared_ptr< mutex >& )
-        {}
+    private:
+        BOOST_MOVABLE_BUT_NOT_COPYABLE(lock)
+    public:
+        lock( const boost::shared_ptr< mutex >& ){}
+        ~lock(){}
+        lock( BOOST_RV_REF( lock ) x ){}
```
Comment (mat007) [inline include/turtle/detail/mutex.hpp]: nit: this needs formatting and new lines

**Comment by mat007** [comment]
Thanks by the way :)

**Comment by Flamefire** [comment]
Done. I think I got all formatting issues and squashed into a single commit. No other changes.

File: include/turtle/detail/function_impl_template.hpp [hunk 16]
```diff
@@ -95,42 +95,55 @@ namespace detail
...
+        public:
             wrapper( const boost::shared_ptr< mutex >& m, expectation_type& e )
-                : wrapper_base< R, expectation_type >( e )
+                : base_type( e )
                 , lock_( m )
             {}
-
-            wrapper once()
+            wrapper( BOOST_RV_REF( wrapper ) x )
+                : base_type( x ), lock_( boost::move( x.lock_) )
```
Comment (mat007) [inline include/turtle/detail/function_impl_template.hpp]: nit: should be two lines
```
    : base_type( x )
    , lock_( boost::move( x.lock_) )
```
(same as the other constructor)

File: include/turtle/detail/mutex.hpp [hunk 17]
```diff
@@ -65,24 +75,37 @@ namespace mock
...
         {}
+        ~scoped_lock()
+        {}
     };
-    struct lock
+    class lock : boost::noncopyable
     {
+    private:
+        BOOST_MOVABLE_BUT_NOT_COPYABLE(lock)
+    public:
```
Comment (mat007) [inline include/turtle/detail/mutex.hpp]: nit: missing a blank line before `public:`

File: include/turtle/detail/mutex.hpp [hunk 18]
```diff
@@ -36,25 +38,33 @@ namespace detail
...
+        {
+            x.m_.reset();
+        }
+        lock& operator=( BOOST_RV_REF( lock ) x )
+        {
+            m_ = x.m_;
+            x.m_.reset();
+            return *this;
+        }
     private:
```
Comment (mat007) [inline include/turtle/detail/mutex.hpp]: nit: probably needs a blank line before `private:`

File: include/turtle/detail/mutex.hpp [hunk 19]
```diff
@@ -36,25 +38,33 @@ namespace detail
...
         ~lock()
         {
             if( m_ )
                 m_->unlock();
         }
-
+        lock( BOOST_RV_REF( lock ) x )
+            : m_( x.m_ )
+        {
+            x.m_.reset();
```
Comment (mat007) [inline include/turtle/detail/mutex.hpp]: Shouldn't that be a `boost::move`?
```
    m_( boost::move( x.m_ ) )
```
?

File: include/turtle/detail/mutex.hpp [hunk 20]
```diff
@@ -36,25 +38,33 @@ namespace detail
...
+        }
+        lock& operator=( BOOST_RV_REF( lock ) x )
+        {
+            m_ = x.m_;
+            x.m_.reset();
```
Comment (mat007) [inline include/turtle/detail/mutex.hpp]: Same here
```
    m_ = boost::move( x.m_ );
```
?

File: include/turtle/detail/mutex.hpp (hunk 19 above)
Comment (Flamefire) [reply include/turtle/detail/mutex.hpp]: No. I need deterministic behaviour here: The other value **must** be NULL so the lock is not unlocked twice. I had the move there and found at least 1 implementation of shared_ptr that did not reset the moved-from value to NULL

Comment (mat007) [reply include/turtle/detail/mutex.hpp]: Sounds to me like a bug in that implementation of shared_ptr, but fair enough.

Comment (mat007) [reply include/turtle/detail/mutex.hpp]: Could be a swap here in the constructor I suppose, but never mind :)

Comment (Flamefire) [reply include/turtle/detail/mutex.hpp]: > Sounds to me like a bug in that implementation of shared_ptr, but fair enough.

It isn't. A "moved from value" has undefined, but valid state. So in the case of a shared_ptr it could do a simple copy and be correct. If at all it is a missed optimization possibility. Still: You can't rely on it being a specific value, so better be safe. Reset is used in both cases for consistency.

**Comment by Flamefire** [comment]
Build failures on travis are connection timeouts.

**Comment by Flamefire** [comment]
@mat007 CI finished green, only the download failures on travis now.
